[project]
name = "dspy-workshop"
version = "0.1.0"
description = "Workshop code for AI Engineering Code Summit NYC"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"attachments",
	"python-dotenv",
	"dspy",
	"ipykernel",
	"pymupdf4llm",
	"opencv-python>=4.12.0.88",
	"openinference-instrumentation-dspy>=0.1.30",
	"openinference-instrumentation-litellm>=0.1.28",
	"arize-phoenix>=12.16.0",
]
